server:
  port: 8083
spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
  mail:
    host: localhost
    port: 1025        # MailDev SMTP port
    username: noreply@CardioSense.tn
    password:
    properties:
      mail:
        smtp:
          auth: false        # no auth needed for MailDev
          starttls:
            enable: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/