package dev.maram.patient.kafka;

import dev.maram.patient.patient.PatientRequest;
import dev.maram.patient.patient.PatientService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.kafka.annotation.KafkaListener;
import org.springframework.stereotype.Component;

@Component
@RequiredArgsConstructor
@Slf4j
public class PatientEventConsumer {

    private final PatientService patientService;

    @KafkaListener(topics = "patient.registered", groupId = "patient-service-group")
    public void consumeRegistration(PatientRegisteredEvent event) {
        log.info("Received registration from Gateway for: {}", event.getEmail());

        // Map Event to Request record
        PatientRequest request = new PatientRequest(
                null, // ID generated by DB
                event.getDoctorId(),
                event.getFirstName(),
                event.getLastName(),
                event.getAge() != null ? event.getAge() : 0,
                event.getEmail(),
                event.getDateOfBirth(),
                event.getGender()
        );

        patientService.createPatient(request);
    }
}